export const languages = [
  ["af", "Afrikaans"],
  ["sq", "Albanian"],
  ["am", "Amharic"],
  ["ar", "Arabic"],
  ["hy", "Armenian"],
  ["az", "Azerbaijani"],
  ["eu", "Basque"],
  ["be", "Belarusian"],
  ["bn", "Bengali"],
  ["bs", "Bosnian"],
  ["bg", "Bulgarian"],
  ["my", "Burmese"],
  ["ca", "Catalan"],
  ["zh-Hans", "Chinese (Simplified)"],
  ["zh-Hant", "Chinese (Traditional)"],
  ["hr", "Croatian"],
  ["cs", "Czech"],
  ["da", "Danish"],
  ["nl", "Dutch"],
  ["en", "English"],
  ["et", "Estonian"],
  ["fil", "Filipino"],
  ["fi", "Finnish"],
  ["fr", "French"],
  ["gl", "Galician"],
  ["ka", "Georgian"],
  ["de", "German"],
  ["el", "Greek"],
  ["gu", "Gujarati"],
  ["ht", "Haitian Creole"],
  ["ha", "Hausa"],
  ["he", "Hebrew"],
  ["hi", "Hindi"],
  ["hu", "Hungarian"],
  ["is", "Icelandic"],
  ["id", "Indonesian"],
  ["ga", "Irish"],
  ["it", "Italian"],
  ["ja", "Japanese"],
  ["jv", "Javanese"],
  ["kn", "Kannada"],
  ["kk", "Kazakh"],
  ["km", "Khmer"],
  ["ko", "Korean"],
  ["ku", "Kurdish"],
  ["ky", "Kyrgyz"],
  ["lo", "Lao"],
  ["lv", "Latvian"],
  ["lt", "Lithuanian"],
  ["mk", "Macedonian"],
  ["ms", "Malay"],
  ["ml", "Malayalam"],
  ["mr", "Marathi"],
  ["mn", "Mongolian"],
  ["ne", "Nepali"],
  ["no", "Norwegian"],
  ["fa", "Persian"],
  ["pl", "Polish"],
  ["pt", "Portuguese"],
  ["pa", "Punjabi"],
  ["ro", "Romanian"],
  ["ru", "Russian"],
  ["sr", "Serbian"],
  ["sd", "Sindhi"],
  ["si", "Sinhala"],
  ["sk", "Slovak"],
  ["sl", "Slovenian"],
  ["so", "Somali"],
  ["nr", "South Ndebele"],
  ["st", "Southern Sotho"],
  ["es", "Spanish"],
  ["su", "Sundanese"],
  ["sw", "Swahili"],
  ["ss", "Swati"],
  ["sv", "Swedish"],
  ["ta", "Tamil"],
  ["te", "Telugu"],
  ["th", "Thai"],
  ["tr", "Turkish"],
  ["uk", "Ukrainian"],
  ["ur", "Urdu"],
  ["uz", "Uzbek"],
  ["vi", "Vietnamese"],
  ["cy", "Welsh"],
  ["xh", "Xhosa"],
  ["yi", "Yiddish"],
  ["yo", "Yoruba"],
  ["zu", "Zulu"],
].map(([code, name]) => ({ code, name }));

export const glossaryLikeItems = [
  "AI Review Terms",
  "Alignment Exceptions",
  "Book One Glossary",
  "Buddhist Sanskrit",
  "Chapter Titles",
  "Chinese Proper Names",
  "Disciples and Lineages",
  "Editorial Warnings",
  "English House Style",
  "Footnote QA",
  "Gnosis Core Terms",
  "Greek Loanwords",
  "Historical Notes",
  "Image Captions",
  "Japanese Honorifics",
  "Liturgical Names",
  "Meditation Terms",
  "Names of Places",
  "OCR Suspects",
  "Philosophy Terms",
  "QA Review Notes",
  "Quoted Passages",
  "Recurring Spanish Phrases",
  "Sanskrit Names",
  "Section Headings",
  "Technical Terms",
  "Theosophical Vocabulary",
  "Translator Warnings",
  "Vietnamese Preferred Terms",
  "Volume Two Glossary",
  "Western Esotericism",
  "XML Import Notes",
  "Yoga Terms",
  "Zen Terms",
].map((title, index) => ({
  id: `resource-${index + 1}`,
  title,
  subtitle: `${8 + (index % 17)} entries updated recently`,
}));
