const SUPPORTED_LANGUAGE_OPTIONS = [
  ["ab", "Abkhazian"],
  ["aa", "Afar"],
  ["af", "Afrikaans"],
  ["ak", "Akan"],
  ["sq", "Albanian"],
  ["am", "Amharic"],
  ["ar", "Arabic"],
  ["an", "Aragonese"],
  ["hy", "Armenian"],
  ["as", "Assamese"],
  ["av", "Avaric"],
  ["ae", "Avestan"],
  ["ay", "Aymara"],
  ["az", "Azerbaijani"],
  ["bm", "Bambara"],
  ["bn", "Bangla"],
  ["ba", "Bashkir"],
  ["eu", "Basque"],
  ["be", "Belarusian"],
  ["bi", "Bislama"],
  ["bs", "Bosnian"],
  ["br", "Breton"],
  ["bg", "Bulgarian"],
  ["my", "Burmese"],
  ["ca", "Catalan"],
  ["ch", "Chamorro"],
  ["ce", "Chechen"],
  ["zh-Hans", "Chinese (Simplified)"],
  ["zh-Hant", "Chinese (Traditional)"],
  ["cu", "Church Slavic"],
  ["cv", "Chuvash"],
  ["kw", "Cornish"],
  ["co", "Corsican"],
  ["cr", "Cree"],
  ["hr", "Croatian"],
  ["cs", "Czech"],
  ["da", "Danish"],
  ["dv", "Dhivehi"],
  ["nl", "Dutch"],
  ["dz", "Dzongkha"],
  ["en", "English"],
  ["eo", "Esperanto"],
  ["et", "Estonian"],
  ["ee", "Ewe"],
  ["fo", "Faroese"],
  ["fj", "Fijian"],
  ["fi", "Finnish"],
  ["fr", "French"],
  ["ff", "Fula"],
  ["gl", "Galician"],
  ["lg", "Ganda"],
  ["ka", "Georgian"],
  ["de", "German"],
  ["el", "Greek"],
  ["gn", "Guarani"],
  ["gu", "Gujarati"],
  ["ht", "Haitian Creole"],
  ["ha", "Hausa"],
  ["he", "Hebrew"],
  ["hz", "Herero"],
  ["hi", "Hindi"],
  ["ho", "Hiri Motu"],
  ["hu", "Hungarian"],
  ["is", "Icelandic"],
  ["io", "Ido"],
  ["ig", "Igbo"],
  ["id", "Indonesian"],
  ["ia", "Interlingua"],
  ["ie", "Interlingue"],
  ["iu", "Inuktitut"],
  ["ik", "Inupiaq"],
  ["ga", "Irish"],
  ["it", "Italian"],
  ["ja", "Japanese"],
  ["jv", "Javanese"],
  ["kl", "Kalaallisut"],
  ["kn", "Kannada"],
  ["kr", "Kanuri"],
  ["ks", "Kashmiri"],
  ["kk", "Kazakh"],
  ["km", "Khmer"],
  ["ki", "Kikuyu"],
  ["rw", "Kinyarwanda"],
  ["kv", "Komi"],
  ["kg", "Kongo"],
  ["ko", "Korean"],
  ["kj", "Kuanyama"],
  ["ku", "Kurdish"],
  ["ky", "Kyrgyz"],
  ["lo", "Lao"],
  ["la", "Latin"],
  ["lv", "Latvian"],
  ["ii", "Liangshan Yi"],
  ["li", "Limburgish"],
  ["ln", "Lingala"],
  ["lt", "Lithuanian"],
  ["lu", "Luba-Katanga"],
  ["lb", "Luxembourgish"],
  ["mk", "Macedonian"],
  ["mg", "Malagasy"],
  ["ms", "Malay"],
  ["ml", "Malayalam"],
  ["mt", "Maltese"],
  ["gv", "Manx"],
  ["mi", "Maori"],
  ["mr", "Marathi"],
  ["mh", "Marshallese"],
  ["mn", "Mongolian"],
  ["na", "Nauru"],
  ["nv", "Navajo"],
  ["ng", "Ndonga"],
  ["ne", "Nepali"],
  ["nd", "North Ndebele"],
  ["se", "North Sami"],
  ["no", "Norwegian"],
  ["nb", "Norwegian Bokmal"],
  ["nn", "Norwegian Nynorsk"],
  ["ny", "Nyanja"],
  ["oc", "Occitan"],
  ["or", "Odia"],
  ["oj", "Ojibwa"],
  ["om", "Oromo"],
  ["os", "Ossetic"],
  ["pi", "Pali"],
  ["ps", "Pashto"],
  ["fa", "Persian"],
  ["pl", "Polish"],
  ["pt", "Portuguese"],
  ["pa", "Punjabi"],
  ["qu", "Quechua"],
  ["ro", "Romanian"],
  ["rm", "Romansh"],
  ["rn", "Rundi"],
  ["ru", "Russian"],
  ["sm", "Samoan"],
  ["sg", "Sango"],
  ["sa", "Sanskrit"],
  ["sc", "Sardinian"],
  ["gd", "Scottish Gaelic"],
  ["sr", "Serbian"],
  ["sn", "Shona"],
  ["sd", "Sindhi"],
  ["si", "Sinhala"],
  ["sk", "Slovak"],
  ["sl", "Slovenian"],
  ["so", "Somali"],
  ["nr", "South Ndebele"],
  ["st", "Southern Sotho"],
  ["es", "Spanish"],
  ["su", "Sundanese"],
  ["sw", "Swahili"],
  ["ss", "Swati"],
  ["sv", "Swedish"],
  ["ty", "Tahitian"],
  ["tg", "Tajik"],
  ["ta", "Tamil"],
  ["tt", "Tatar"],
  ["te", "Telugu"],
  ["th", "Thai"],
  ["bo", "Tibetan"],
  ["ti", "Tigrinya"],
  ["to", "Tongan"],
  ["ts", "Tsonga"],
  ["tn", "Tswana"],
  ["tr", "Turkish"],
  ["tk", "Turkmen"],
  ["tw", "Twi"],
  ["uk", "Ukrainian"],
  ["ur", "Urdu"],
  ["ug", "Uyghur"],
  ["uz", "Uzbek"],
  ["ve", "Venda"],
  ["vi", "Vietnamese"],
  ["vo", "Volapuk"],
  ["wa", "Walloon"],
  ["cy", "Welsh"],
  ["fy", "Western Frisian"],
  ["wo", "Wolof"],
  ["xh", "Xhosa"],
  ["yi", "Yiddish"],
  ["yo", "Yoruba"],
  ["za", "Zhuang"],
  ["zu", "Zulu"],
];

export const isoLanguageOptions = SUPPORTED_LANGUAGE_OPTIONS.map(([code, name]) => ({
  code,
  name,
}));

const isoLanguageOptionsByCode = new Map(
  isoLanguageOptions.map((option) => [option.code.toLowerCase(), option]),
);

export function findIsoLanguageOption(code) {
  return isoLanguageOptionsByCode.get(String(code ?? "").trim().replaceAll("_", "-").toLowerCase()) ?? null;
}

export function normalizeSupportedLanguageCode(code) {
  return findIsoLanguageOption(code)?.code ?? "";
}
